### ISSUE TITLE
Why I am try run Kotlin is unable

### ISSUE THREAD

**Issue by Alex-Linrk** [formulahendry/vscode-code-runner#123]
when i try to run simple code 
`fun main(args: Array<String>) {
    println("Hello, world!")
}`
the console show this 
`[Running] cd "c:\Users\Administrator\Documents\" && kotlinc firstKotlin.kt -include-runtime -d firstKotlin.jar && java -jar firstKotlin.jar
'kotlinc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

[Done] exited with code=1 in 0.032 seconds`

i can`t understand what`s wrong. and i can`t search anything about this error so i push this issues

**Comment by formulahendry** [comment]
Have you installed Kotlin? And make sure kotlinc is in PATH environment variable.

**Comment by Alex-Linrk** [comment]
@formulahendry thank you for your reply，I am such an idiot, Just install Visual Studio Code Extend Kotlin Language ,I think it must be like Android Studio Plugin work, but it just a Syntax highlighter Support.
Thank you again.

**Comment by bidisha0101** [comment]
hi guys 
i am having a different kind of error in vs code 
cd "c:\Users\bidis\Projects\my-coffee-review\kotlin\" && kotlinc helloworld.kt -include-runtime -d helloworld.jar && java -jar helloworld.jar
Java HotSpot(TM) 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
exception: java.lang.ArrayIndexOutOfBoundsException: Index 11171 out of bounds for length 11171
	at org.jetbrains.org.objectweb.asm.ClassReader.readUnsignedShort(ClassReader.java:2464)
	at org.jetbrains.org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:2525)
	at org.jetbrains.org.objectweb.asm.ClassReader.readModule(ClassReader.java:761)
	at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:646)
	at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:507)
	at org.jetbrains.kotlin.resolve.jvm.modules.JavaModuleInfo$Companion.read(JavaModuleInfo.kt:67)
	at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder.findSystemModule(CliJavaModuleFinder.kt:44)
	at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder.access$findSystemModule(CliJavaModuleFinder.kt:25)
	at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder$systemModules$1.invoke(CliJavaModuleFinder.kt:37)
	at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder$systemModules$1.invoke(CliJavaModuleFinder.kt:25)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:149)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:109)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:133)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:254)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:241)
	at kotlin.sequences.SequencesKt___SequencesKt.none(_Sequences.kt:1239)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.addModularRoots(ClasspathRootsResolver.kt:227)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.computeRoots(ClasspathRootsResolver.kt:124)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:79)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:230)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:114)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:409)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:286)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createEnvironmentWithScriptingSupport(K2JVMCompiler.kt:276)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:196)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:63)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:109)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:53)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler$Companion.main(K2JVMCompiler.kt:343)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.main(K2JVMCompiler.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.jetbrains.kotlin.preloading.Preloader.run(Preloader.java:81)
	at org.jetbrains.kotlin.preloading.Preloader.main(Preloader.java:43)


[Done] exited with code=2 in 1.792 seconds

some help please
