### ISSUE TITLE
usage with nodemon

### ISSUE THREAD

**Issue by rickmed** [formulahendry/vscode-code-runner#13]
I want to do nodemon somefile.js (nodemon installed locally so I need to go through the npm script).

so in scripts in package.json I have

    "mon": "nodemon",

and in code-runner execmap settings:
   "mon": "npm run mon",

I get this:
```
> playground@1.0.0 mon c:\Users\rickm\Documents\Google Drive\Side-projects\Programming\NodeJS\playground-js
> nodemon "c:\Users\rickm\Documents\Google Drive\Side-projects\Programming\NodeJS\playground-js\server_frameworks\spirit\return-early.js"

[nodemon] 1.10.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node "c:\\Users\\rickm\\Documents\\Google Drive\\Side-projects\\Programming\\NodeJS\\playground-js\\server_frameworks\\spirit\\return-early.js"`
module.js:442
    throw err;
    ^

Error: Cannot find module 'c:\Users\rickm\Documents\Google Drive\Side-projects\Programming\NodeJS\playground-js\"c:\Users\rickm\Documents\Google'
```

**Comment by formulahendry** [comment]
Hi @rickmed , do you expect to run `npm run mon somefile.js`? And what does `"mon": "nodemon"` in package.json mean?

**Comment by rickmed** [comment]
is just a npm script in the package.json (calling nodemon there calls the local install, not the global). I call nodemon through the npm script to use the local install, otherwise I would need to add a relative path to the local node_modules/.bin folder (which I don't think is supported by the vs-code-runner)

**Comment by formulahendry** [comment]
Could you please show the whole output form Output Window of Code Runner?
```
[Running] npm run mon "somefile"
...
[Done] ...
```

**Comment by rickmed** [comment]
not super useful I believe...
```
[Running] npm run mon "c:\Users\rickm\Documents\Google Drive\Side-projects\Programming\NodeJS\playground-js\nodejs_native\server.js"

> playground@1.0.0 mon c:\Users\rickm\Documents\Google Drive\Side-projects\Programming\NodeJS\playground-js
> nodemon  "c:\Users\rickm\Documents\Google Drive\Side-projects\Programming\NodeJS\playground-js\nodejs_native\server.js"

[nodemon] 1.10.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node "c:\\Users\\rickm\\Documents\\Google Drive\\Side-projects\\Programming\\NodeJS\\playground-js\\nodejs_native\\server.js"`
module.js:442
    throw err;
    ^

Error: Cannot find module 'c:\Users\rickm\Documents\Google Drive\Side-projects\Programming\NodeJS\playground-js\"c:\Users\rickm\Documents\Google'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by formulahendry** [comment]
If you run `npm run mon "c:\Users\rickm\Documents\Google Drive\Side-projects\Programming\NodeJS\playground-js\nodejs_native\server.js"` in cmd, will it work?

**Comment by rickmed** [comment]
you are right. It is a nodemon's bug.

**Comment by rickmed** [comment]
#https://github.com/remy/nodemon/issues/474

**Comment by rickmed** [comment]
#https://github.com/remy/nodemon/issues/474

**Comment by formulahendry** [comment]
Thus, closing it.
