### ISSUE TITLE
Unexpected identifier error

### ISSUE THREAD

**Issue by amurad** [formulahendry/vscode-code-runner#173]
I frequenty get this error when running javascript with Ctrl-Alt-N. It goes away after I repeatedly try to save and run. There are no issues if I run the same script from command line using node test.js.

    (function (exports, require, module, __filename, __dirname) { [Running] node 
            C:\Users\def\Projects\Innovia3d\spire-electron\tempCodeRunnerFile.javascript"
                                                                            ^^^^

    SyntaxError: Unexpected identifier
        at createScript (vm.js:74:10)
        at Object.runInThisContext (vm.js:116:10)
        at Module._compile (module.js:537:28)
        at Object.Module._extensions..js (module.js:584:10)
        at Module.load (module.js:507:32)
        at tryModuleLoad (module.js:470:12)
        at Function.Module._load (module.js:462:3)
        at Function.Module.runMain (module.js:609:10)
        at startup (bootstrap_node.js:158:16)
        at bootstrap_node.js:598:3

    [Done] exited with code=1 in 0.362 seconds`

**Comment by formulahendry** [comment]
As you can see, the file is **tempCodeRunnerFile.javascript**. It indicates that you have selected part of the code snippet and run it. Is it intended? If not, you may want not to have any selection of code. Or you may want to run the file by ignoring the selection, refer to #156
