### ISSUE TITLE
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

### ISSUE THREAD

**Issue by treymerkley** [formulahendry/vscode-code-runner#222]
When I attempt to run a segment of Python code, this is what is returned: 

```
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "/home/trey/Homework/DataScience/tempCodeRunnerFile.py", line 1, in <module>
    import pandas as pd
  File "/usr/local/lib/python2.7/dist-packages/pandas/__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: numpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

[Done] exited with code=1 in 4.087 seconds
```

My python version is Anaconda, and my VSCode is Linux 64-bit 1.18.1

**Comment by formulahendry** [comment]
Did you intend to select part of the code to run? How about running the same code in terminal?

**Comment by treymerkley** [comment]
Yeah, sorry about that. I ran 
```
import pandas as pd
web_stats = {'Day' : [1, 2, 3, 4, 5, 6],
            'Visitors' : [43, 34, 65, 56, 29, 76],
            'Bounce Rate' : [65, 67, 78, 65, 45, 52]}
                    
df = pd.DataFrame(web_stats)
```
Running in python terminal produces no ill effects.

**Comment by formulahendry** [comment]
Could you try running without selecting part of the code?

**Comment by treymerkley** [comment]
Just tried running it without selecting part of the code. It still returns the same error.

**Comment by formulahendry** [comment]
Could you try below setting and run again?
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by treymerkley** [comment]
fixed all up! Thanks!

**Comment by formulahendry** [comment]
Good to know! Closing it then.
