### ISSUE TITLE
Cannot run .exe files

### ISSUE THREAD

**Issue by Salil03** [formulahendry/vscode-code-runner#337]
Here is a part of my settings.json

```
"code-runner.executorMapByFileExtension": {
        ".vb": "cd $dir && vbc /nologo $fileName && $dir$fileNameWithoutExt",
        ".vbs": "cscript //Nologo",
        ".scala": "scala",
        ".jl": "julia",
        ".cr": "crystal",
        ".ml": "ocaml",
        ".exs": "elixir",
        ".hx": "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt",
        ".rkt": "racket",
        ".ahk": "autohotkey",
        ".au3": "autoit3",
        ".kt": "cd $dir && kotlinc $fileName -include-runtime -d $fileNameWithoutExt.jar && java -jar $fileNameWithoutExt.jar",
        ".kts": "kotlinc -script",
        ".dart": "dart",
        ".pas": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
        ".pp": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
        ".d": "cd $dir && dmd $fileName && $dir$fileNameWithoutExt",
        ".hs": "runhaskell",
        ".nim": "nim compile --verbosity:0 --hints:off --run",
        ".csproj": "dotnet run --project",
        ".fsproj": "dotnet run --project",
        ".exe": "cd $dir $$ $fileName"
    }
```

But when I right click on an .exe an click run code, nothing happens. What am I doing wrong ?

OS: Windows 10 64-bit
VS Code: Version 1.25

**Comment by formulahendry** [comment]
Did you see anything as below? You may want to open VS Code ad admin
![image](https://user-images.githubusercontent.com/1050213/43564647-3815c756-965a-11e8-8197-14f15de11418.png)

**Comment by Salil03** [comment]
No I didn't see anything like that

**Comment by Salil03** [comment]
And it doesn't work even if I run it as administrator.

**Comment by formulahendry** [comment]
What if you run other types of code?

**Comment by Salil03** [comment]
.cpp works and .py also works

**Comment by Salil03** [comment]
.bat does not work

**Comment by Salil03** [comment]
code-runner.executorMapByFileExtension does not work but all programming languages work

**Comment by formulahendry** [comment]
What if you run `.csproj` file?

**Comment by Salil03** [comment]
How do I do that ?

**Comment by formulahendry** [comment]
Just create a `abcd.csproj` file with any content, then `Run Code`

**Comment by Salil03** [comment]
ok

**Comment by Salil03** [comment]
Yes it works

**Comment by formulahendry** [comment]
Could you remove below setting and try again?
```
"files.associations": {
        ".exe": "executable"
    }
```
And when you run `.exe`, nothing in Output Channel? And could you see any error in `Help`->`Toggle Developer Tools`->`Console`?

**Comment by Salil03** [comment]
After I remove the setting the same thing happens.

I see nothing in the Output Channel

Here is what I see in Developer Tools Console:
```
[Extension Host] rejected promise not handled within 1 second
t.log @ workbench.main.js:sourcemap:270
t._logExtensionHostMessage @ workbench.main.js:sourcemap:3045
(anonymous) @ workbench.main.js:sourcemap:3041
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
workbench.main.js:sourcemap:1376   ERR cannot open file:///c%3A/Users/prash/Documents/Salil/Programming/Programs/C%2B%2B/Exercises/Chapter%203/Ex%2011.exe. Detail: File seems to be binary and cannot be opened as text: Error: cannot open file:///c%3A/Users/prash/Documents/Salil/Programming/Programs/C%2B%2B/Exercises/Chapter%203/Ex%2011.exe. Detail: File seems to be binary and cannot be opened as text
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4150:832
    at Object.v [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:375)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:592)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._chainedError (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:255)
    at n (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:115)
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:736)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:184)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._setCompleteValue (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:590)
    at Object.v [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:357)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:592)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._chainedError (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:255)
    at n (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:115)
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:736)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:184)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._setCompleteValue (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:590)
    at Object.v [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:357)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:592)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._chainedError (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:255)
    at n (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:115)
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:736)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:184)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._setCompleteValue (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:590)
    at Object.v [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:357)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:592)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._chainedError (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:255)
    at n (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:115)
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:736)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:184)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._setCompleteValue (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:590)
    at Object.v [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:357)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:592)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._chainedError (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:255)
    at n (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:115)
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:736)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:184)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._setCompleteValue (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:590)
    at Object.v [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:357)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:592)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._error (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:413)
    at l (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:962)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:70
    at Object.v [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:375)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:592)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._error (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:413)
    at v (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3174:344)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3175:224
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:157:366)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3175:172
    at callback (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\graceful-fs\polyfills.js:128:19)
    at FSReqWrap.wrapper [as oncomplete] (original-fs.js:629:17)
```

**Comment by Salil03** [comment]
Did you find a solution ?

**Comment by formulahendry** [comment]
Oh, I could repro this issue now. This is a bug. I will take a look at this.

**Comment by Salil03** [comment]
Thank You

**Comment by Salil03** [comment]
When will it be corrected ? Is there a alternative currently ?

**Comment by formulahendry** [comment]
You could use "code-runner.customCommand" as workaround

**Comment by Salil03** [comment]
How do I use that because when I tried it, even that was not working

**Comment by formulahendry** [comment]
`"code-runner.customCommand": "foo/bar/abc.exe"`

**Comment by Salil03** [comment]
what does foo/bar/abc.exe mean ? I want it for any exe file with any name

**Comment by formulahendry** [comment]
In that case, there is no good workaround.

**Comment by Salil03** [comment]
Ok when will the bug be repaired

**Comment by Salil03** [comment]
and what exactly does the error message mean  ?

**Comment by Salil03** [comment]
The funny thing is that it used to work 3 months earlier!

**Comment by formulahendry** [comment]
Seems VS Code has API change, .exe would not be opened by default now. If you open a .exe file as a text, then you could run it.

**Comment by Salil03** [comment]
How do I open .exe as a text ?

**Comment by formulahendry** [comment]
![image](https://user-images.githubusercontent.com/1050213/43675018-9db8e550-980f-11e8-9f88-d152592bbf51.png)

**Comment by Salil03** [comment]
Ok thanks :)

**Comment by Salil03** [comment]
Just for my curiosity, when are you planning to fix the bug ?

**Comment by formulahendry** [comment]
No ETA for now. If you'd like to have a PR to fix that, that would be great. :)

**Comment by Salil03** [comment]
Does it mean Pull Request

**Comment by formulahendry** [comment]
Yes

**Comment by Salil03** [comment]
I don't think I have the knowledge to fix the bug. Sorry 😔☹️

**Comment by aandrejevas** [comment]
Hello, any progress on this issue?

**Comment by mturvillehei** [comment]
I've also run into this problem.

**Comment by Kavex71** [comment]
No.  If I'm worse, I'm new to this, I barely understand a little, I really want to learn and I'm trying hard every day.
