### ISSUE TITLE
Get error on running `ts-node` on TypeScript files

### ISSUE THREAD

**Issue by nikitavoloboev** [formulahendry/vscode-code-runner#353]
Below is the error:
```
[Running] ts-node "/Users/nikivi/src/test/ts-test/test.ts"

/Users/nikivi/.npm-global/lib/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS5023: Unknown compiler option 'exclude'.

    at createTSError (/Users/nikivi/.npm-global/lib/node_modules/ts-node/src/index.ts:261:12)
    at Object.register (/Users/nikivi/.npm-global/lib/node_modules/ts-node/src/index.ts:265:42)
    at Object.<anonymous> (/Users/nikivi/.npm-global/lib/node_modules/ts-node/src/bin.ts:113:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)

[Done] exited with code=1 in 0.332 seconds
```

I have both [ts-node](https://github.com/TypeStrong/ts-node) and [typescript](https://www.npmjs.com/package/typescript) installed globally with `npm i -g`.

I can run the above file in my shell but not with Code Runner:

```
❯  ts-node "/Users/nikivi/src/test/ts-test/test.ts"
test
```

**Comment by formulahendry** [comment]
Did you try closing all VS Code, and start VS Code and then try again?

**Comment by nikitavoloboev** [comment]
> Did you try closing all VS Code, and start VS Code and then try again?

Tried that. Same error:

```
[Running] ts-node "/Users/nikivi/src/test/ts-test/test.ts"

/Users/nikivi/.npm-global/lib/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS5023: Unknown compiler option 'exclude'.

    at createTSError (/Users/nikivi/.npm-global/lib/node_modules/ts-node/src/index.ts:261:12)
    at Object.register (/Users/nikivi/.npm-global/lib/node_modules/ts-node/src/index.ts:265:42)
    at Object.<anonymous> (/Users/nikivi/.npm-global/lib/node_modules/ts-node/src/bin.ts:113:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)

[Done] exited with code=1 in 0.381 seconds
```

**Comment by formulahendry** [comment]
Please use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by ak99372** [comment]
I think the issue is that the code runner executes command in **root folder**!  If your package/project (including tsconfig) is a sub folder you will run into this issue. 
The solution is then to make sure the project's folder is in your workspace on its own (you can just -re-add the folder into workspace again but make sure to run the run from there).
