### ISSUE TITLE
utf-8 is not supported

### ISSUE THREAD

**Issue by alking9950** [formulahendry/vscode-code-runner#379]
Traceback (most recent call last):
  File "f:\Users\mustafa\Documents\GitHub\page\uuu.py", line 1, in <module>
    print('\u826f\u3044')
  File "C:\Program Files\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>

**Comment by formulahendry** [comment]
Please use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```
