### ISSUE TITLE
SyntaxError: Unexpected token : ES6

### ISSUE THREAD

**Issue by phill8686** [formulahendry/vscode-code-runner#400]
Hi

I am getting a syntax error when running ES6 is says in post #257 that it is related to the node.js version what version do I need to run I am currently running 8.11.2.

Great extension by the way.

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
Thanks

Phill

**Comment by BaldestFrog** [comment]
Same
