### ISSUE TITLE
cwd

### ISSUE THREAD

**Issue by rickmed** [formulahendry/vscode-code-runner#5]
When running, for example, a js (node) script, it sets the cwd to the global node installation so any modules you have locally installed won't recognize and err...

**Comment by formulahendry** [comment]
Provide a config entry to set the cwd or set the cwd as the root folder opened in VS Code. Which one do you prefer?

**Comment by rickmed** [comment]
@formulahendry Set the cwd as the root folder opened in VS Code as default unless an optional config option is set?

**Comment by formulahendry** [comment]
Sounds good! Let me have a try.

**Comment by formulahendry** [comment]
Hi @rickmed , I have resolved this issue as we discussed. Please install the latest version and have a try. Let me know if it is working as you expected.

**Comment by rickmed** [comment]
@formulahendry 
 not working.

this is what I'm running (play.js in the root vscode dir)

```
console.log(process.cwd())
require('tape')
```

I get

```
c:\Users\rickm\Documents\Google Drive\Side-projects\Programming\NodeJS\js-playground
module.js:442
    throw err;
    ^

Error: Cannot find module 'tape'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\rickm\AppData\Local\Temp\aqmsegqipe.js:4:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by formulahendry** [comment]
Just find the issue, please try latest version 0.1.3  :smiley:
