### ISSUE TITLE
JavaSript: TypeError

### ISSUE THREAD

**Issue by raziEiL** [formulahendry/vscode-code-runner#519]
- VS Code Version: 1.37
- OS Version: Win 10 x64
- Code Runner Version: 0.9.14

**Describe the bug**
I'm wrote a simple IIFE (Immediately Invoked Function Expression) function and got an error.
```
(function sum(a, b) {
    console.log(a + b); // 5
})(2, 3);
```

> TypeError: console.log(...) is not a function
>     at Object.<anonymous> (d:\web\github.io\main\practice\programming.js:177:1)
>     at Module._compile (internal/modules/cjs/loader.js:776:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Actual behavior**
Logs console output: 5

**Comment by raziEiL** [comment]
my bad
