### ISSUE TITLE
code runner cant run pandas and numpy

### ISSUE THREAD

**Issue by boazdori** [formulahendry/vscode-code-runner#567]
Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

run code import numpy in the editor
I am getting
Traceback (most recent call last):
File "c:\Users\user\Documents\Visual Studio 2017\Projects\test1.py", line 7, in
import pandas as pd
File "C:\Users\user\Anaconda3\lib\site-packages\pandas_init_.py", line 17, in
"Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy:
if i try to run python -c "import numpy" at the prompt works
if i use run file in terminal in vs code the code works
the only place it dosn't work is when using the upper right hand button run code which sends to the output window.
code runner runs other anaconda libraries

**Comment by munich-ml** [comment]
Hi boazdori,

I'm also having the issue, that code-runner (within VS Code) raises 'ImportError' from numpy, while the script works just fine from terminal. 

Did you find a solution?

**Comment by boazdori** [comment]
the virtual env wasn't working for me ones that was sorted it started
working
